name: Stuff and Things
title: Jared Morgan
description: "Jared Morgan's blog about random stuff and good things"
logo: assets/images/logotype.png
favicon: assets/images/favicon.ico
baseurl: ''
disqus: jaredmorgs
include:
  - _pages
permalink: '/:title/'
authors:
  jared:
    name: Jared Morgan
    site: 'https://jaredleonmorgan.net'
    avatar: assets/images/jared.png
    bio: >-
      Technical writer, product person, VR junkie.
    email: jaredleonmorgan@gmail.com
    twitter: 'https://twitter.com/jaredmorgs'
plugins:
  - jekyll-asciidoc
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
paginate: 6
paginate_path: '/page:num/'
asciidoctor:
  safe: safe
  liquid: true
  source-highlighter: pygments
  pygments-css: class
  pygments-stylesheet: '' 
  attributes:
    imagesdir: /assets/images
    icons: font
#markdown: kramdown
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    block:
#      line_numbers: true
adsense: disabled
adsense-data-ad-client: ca-pub-3412143450191416
adsense-data-ad-slot: '1363087678'
lazyimages: enabled
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
  - ads.txt
url: ''
whitelist:
- jekyll-asciidoc